### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by michabbb** [c-tanner/laravel-deep-sync#1]
https://github.com/c-tanner/laravel-deep-sync/blob/75f9fa074d5266444a1a45e9a086c35fa04c72b8/src/Observers/DeepSync.php#L191

thanks for this package !! 👍
the first question that came into my mind: if a user has 10k posts, are you doing 10k updates ?
because based on the foreign key it could be done with only one update, of course ;)

does it only work with the column "deleted_at" or is it possible to change that name ?

thanks!

**Comment by c-tanner** [comment]
Hey @michabbb 👋  First issue, nice :) Thanks!

> if a user has 10k posts, are you doing 10k updates ?

Short answer, yes. The reason this has to be done one-by-one is due to how Laravel's model events work. When querying the database directly to perform updates, model events do not fire. From the [docs](https://laravel.com/docs/5.3/eloquent#updates):

> When issuing a mass update via Eloquent, the saved and updated model events will not be fired for the updated models. This is because the models are never actually retrieved when issuing a mass update.

Since we rely on model events to fire in order for everything downstream to also pick up the updates (Model A triggers Model B, Model B triggers Model C, ...), this is unfortunately the only way to make that happen.

> does it only work with the column "deleted_at" or is it possible to change that name

If you're asking about the `delete()` events, this seems to be possible in Laravel by [declaring a const in your model with the desired column name](https://stackoverflow.com/questions/42049726/use-custom-soft-deleted-column-in-laravel):

`const DELETED_AT = 'my_soft_delete_column';`

While the current version of DeepSync does need the `deleted_at` column for `delete()` events, I'll work on a feature for this!

For attributes that should be updated on `save()` or `update()` events, those can be declared in the `$syncable` array.

Hope this helps! Let me know if you have any other questions

**Comment by c-tanner** [comment]
Merging the feature that will support the custom column name now. Thanks for the suggestion!
